package com.bjpowernode.crm.settings.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.loginAct
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String loginact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.loginPwd
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.expireTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lockState
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String lockstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.deptno
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.allowIps
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String allowips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.editTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.editBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    private String editby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.loginAct
     *
     * @return the value of tbl_user.loginAct
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getLoginact() {
        return loginact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.loginAct
     *
     * @param loginact the value for tbl_user.loginAct
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setLoginact(String loginact) {
        this.loginact = loginact == null ? null : loginact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.loginPwd
     *
     * @return the value of tbl_user.loginPwd
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.loginPwd
     *
     * @param loginpwd the value for tbl_user.loginPwd
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.expireTime
     *
     * @return the value of tbl_user.expireTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.expireTime
     *
     * @param expiretime the value for tbl_user.expireTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setExpiretime(String expiretime) {
        this.expiretime = expiretime == null ? null : expiretime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lockState
     *
     * @return the value of tbl_user.lockState
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getLockstate() {
        return lockstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lockState
     *
     * @param lockstate the value for tbl_user.lockState
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setLockstate(String lockstate) {
        this.lockstate = lockstate == null ? null : lockstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.deptno
     *
     * @return the value of tbl_user.deptno
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.deptno
     *
     * @param deptno the value for tbl_user.deptno
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno == null ? null : deptno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.allowIps
     *
     * @return the value of tbl_user.allowIps
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getAllowips() {
        return allowips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.allowIps
     *
     * @param allowips the value for tbl_user.allowIps
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setAllowips(String allowips) {
        this.allowips = allowips == null ? null : allowips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createTime
     *
     * @return the value of tbl_user.createTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createTime
     *
     * @param createtime the value for tbl_user.createTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createBy
     *
     * @return the value of tbl_user.createBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createBy
     *
     * @param createby the value for tbl_user.createBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.editTime
     *
     * @return the value of tbl_user.editTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.editTime
     *
     * @param edittime the value for tbl_user.editTime
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.editBy
     *
     * @return the value of tbl_user.editBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.editBy
     *
     * @param editby the value for tbl_user.editBy
     *
     * @mbggenerated Sun Nov 08 16:06:30 GMT+08:00 2020
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }
}